default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: flax_development
test:
  <<: *default
  database: flax_test

production:
  <<: *default
  database: flax_production
  username: postgres
  password: postgres
